Added `workspace:` and `resolution: fields`
dart-lang/tools pull request #1948
Opened 2024-12-23 18:53 UTC by Levi-Lesches

Fixes #1814 by adding `Pubspec.workspace` (`List<String>?`) and `Pubspec.resolution` (`String?`). Didn't bump the changelog or version yet because I didn't want to conflict with #1946, but I can do that once it's merged (or rebase this onto that branch). 

Does not check that `dart: ^3.6.0`, leaving that up to [these lines in Pub](https://github.com/dart-lang/pub/blob/58de642dc1d07601f6eb2b4ecd94555c0210106b/lib/src/pubspec.dart#L110-L122). 

An omitted `resolution:` or `workspace` field is treated as null. 

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

2024-12-23 19:01 UTC, Levi-Lesches commented
Okay seems I did need to bump -- done. Also, what are your thoughts on adding 

- `Pubspec.isWorkspace`: returns true if `workspace != null` 
- `Pubspec.isInWorkspace`: returns true if `resolution == 'workspace'`

2024-12-23 19:12 UTC, kevmoo commented
Tests? You added a changelog entry? *swoon*

2024-12-27 20:02 UTC, kevmoo commented
> Okay seems I did need to bump for the CI to pass -- done. Also, what are your thoughts on

great questions

> * `Pubspec.isWorkspaceRoot`: returns true if `workspace != null`
> * `Pubspec.isInWorkspace`: returns true if `resolution == 'workspace'`

These seem like just adding complexity. Would like to keep this simple.

> * changing `Pubspec.resolution` from a `String?` to a `Resolution`, as [Pub does](https://github.com/dart-lang/pub/blob/58de642dc1d07601f6eb2b4ecd94555c0210106b/lib/src/pubspec.dart#L123-L132)


Ditto. No clue where pub will go. Leaving it as a string for now is most simple.

2024-12-27 20:03 UTC, kevmoo requested changes
Two things then I'll land it. Amazing. Thanks!

2024-12-27 20:03 UTC, kevmoo commented on pkgs/pubspec_parse/CHANGELOG.md
> +## 1.5.0
```suggestion
## 1.5.0-wip
```

2024-12-27 20:03 UTC, kevmoo commented on pkgs/pubspec_parse/pubspec.yaml
> +version: 1.5.0
```suggestion
version: 1.5.0-wip
```

Since we're not quite ready to publish.

2024-12-27 20:33 UTC, Levi-Lesches commented
Done, thanks!

2024-12-27 22:28 UTC, kevmoo approved these changes

2024-12-27 22:28 UTC, merged

2024-12-30 19:16 UTC, gabrielgarciagava commented
@kevmoo When can we expect this to be published?

2025-01-02 17:02 UTC, kevmoo commented
> @kevmoo When can we expect this to be published?

We have a few other PRs we need to land...

2025-01-07 10:57 UTC, spydon commented
@kevmoo would it be possible to publish this first? :innocent:
We're currently blocked on releasing Melos with the Pub Workspaces feature until this is released, since pub doesn't allow git dependencies.

2025-01-07 16:19 UTC, devoncarew commented
We'd like to land https://github.com/dart-lang/tools/pull/1952 first (if that doesn't happen soon, we can publish and rebase that PR for a future -wip version).

2025-01-07 18:25 UTC, devoncarew commented
@Levi-Lesches (and @Dhruv-Maradiya) thanks for your contributions. This was published along with the related https://github.com/dart-lang/tools/pull/1952.