Fix(html): Handle <br> elements to insert line breaks in text
dart-lang/tools pull request #1950
Opened 2024-12-25 12:47 UTC by Dhruv-Maradiya

Fixes #1090 by updating the DOM parser to handle `<br>` elements and insert line breaks (`\n`) when converting HTML content to plain text.

Initially, I thought adding a simple condition might not be a reliable solution. So, I decided to check how HTML-to-text conversion is handled in Chromium and found a similar approach. Here's the [link](https://chromium.googlesource.com/chromium/blink/+/refs/heads/main/Source/core/dom/Node.cpp#1244). 

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

2025-04-17 12:53 UTC, HosseinYousefi requested changes

2025-04-17 12:53 UTC, HosseinYousefi commented on pkgs/html/lib/dom_parsing.dart
> +    if (node.localName == 'br') {
This can be separate `isElementBr` function. Is this if statement enough to recognize it?

2025-04-17 12:53 UTC, HosseinYousefi commented on pkgs/html/test/parser_feature_test.dart
> +    expect(e.text, 'foo\nbarbaz\n');
I wouldn't change the behavior of `.text`, in the link you shared we had a function with an explicit boolean like `textContent({bool convertBRsToNewlines = false})`, I'd prefer to add that instead.

2025-04-19 07:56 UTC, Dhruv-Maradiya commented
Hey, thanks for reviewing this! 🙌
It’s been a few months since I worked on it, and I was still getting familiar with the codebase at the time — so I’ll need to refresh myself on the changes.
I'll take a look as soon as I can. Appreciate your feedback!

2025-10-07 12:10 UTC, mosuem commented
@Dhruv-Maradiya  Just a friendly ping as I am looking through PRs - is there intention to land this?

2025-10-08 04:14 UTC, Dhruv-Maradiya commented
Hey @mosuem, sorry for the delay! I’ll try to wrap this up ASAP, most likely today.

2025-10-13 15:44 UTC, mosuem commented
Friendly ping :) (No pressure, just happened to walk by this tab in my browser)

2025-12-12 13:05 UTC, mosuem commented
@HosseinYousefi could you take another look?

2025-12-12 13:58 UTC, HosseinYousefi approved these changes

2025-12-12 14:50 UTC, HosseinYousefi requested changes

2025-12-12 14:50 UTC, HosseinYousefi commented on pkgs/html/lib/dom.dart
> +bool isElementBr(Element element) {
This can be private.

2025-12-12 14:50 UTC, HosseinYousefi commented on pkgs/html/CHANGELOG.md
> +- Fix a bug in DOM parsing where `<br>` tags does not create a new line when html is converted to text.
It's no longer a bug then, change the changelog entry to convey adding a new `textContent` method instead.

2025-12-14 17:21 UTC, HosseinYousefi approved these changes

2026-06-22 05:46 UTC, mosuem commented
@Dhruv-Maradiya do you intend to land this? Otherwise I would close this rather old PR.

2026-06-22 06:01 UTC, Dhruv-Maradiya commented
Hey @mosuem I belive everything is done from my side, pr is approved. 
Let me know if I missed something

2026-06-22 06:08 UTC, mosuem approved these changes

2026-06-22 06:09 UTC, merged

2026-06-22 06:09 UTC, mosuem commented
Thanks! I forgot about the write permissions thing on this repo...